const COLECCIONES_PROTEGIDAS = [
  'USUARIOS',
  'CONFIGURACION',
  'EMPLEADOS_REF',
  'EMPLEADOS',
  'COMPETENCIAS',
  'NOTAS',
  'SICK_LEAVES',
  'BAJAS',
  'INCIDENT_LOG',
  'BAJAS_METADATA',
  'APP_GENERATED_PUNCHES',
  'EMPLOYEE_ACCESS_LOG',
  'EMPLOYEE_AUDIT_LOG',
  'TRABAJOS',
  'COMPETENCIAS_DEF'
];

const COLECCIONES_LEGADO = [
  'EMPLEADOS'
];

module.exports = {
  COLECCIONES_PROTEGIDAS,
  COLECCIONES_LEGADO
};
